name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  codecov:
    name: Code coverage
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-02-01
          components: tarpaulin

      - name: Set up rust cache
        uses: Swatinem/rust-cache@v2
        with:
            cache-on-failure: true

      - name: Run cargo fmt
        run: cargo tarpaulin --verbose --engine llvm --release --out Xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
